// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROYECTO_SUBASTA.Infrastructure.Data;

#nullable disable

namespace PROYECTO_SUBASTA.Infrastructure.Migrations
{
    [DbContext(typeof(SubastaDbContext))]
    [Migration("20260911040541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoDisponible = 0.00m,
                            SaldoRetenido = 0.00m,
                            SaldoTotal = 0.00m,
                            UsuarioId = 1,
                            Version = 0
                        },
                        new
                        {
                            Id = 2,
                            SaldoDisponible = 105000.00m,
                            SaldoRetenido = 45000.00m,
                            SaldoTotal = 150000.00m,
                            UsuarioId = 2,
                            Version = 0
                        },
                        new
                        {
                            Id = 3,
                            SaldoDisponible = 200000.00m,
                            SaldoRetenido = 0.00m,
                            SaldoTotal = 200000.00m,
                            UsuarioId = 3,
                            Version = 0
                        },
                        new
                        {
                            Id = 4,
                            SaldoDisponible = 500.00m,
                            SaldoRetenido = 0.00m,
                            SaldoTotal = 500.00m,
                            UsuarioId = 4,
                            Version = 0
                        });
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlIcono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología",
                            UrlIcono = ""
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables",
                            UrlIcono = ""
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria",
                            UrlIcono = ""
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos",
                            UrlIcono = ""
                        });
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubastaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2026, 9, 11, 3, 50, 40, 691, DateTimeKind.Utc).AddTicks(1139),
                            Monto = 35000.00m,
                            SubastaId = 1,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 2,
                            FechaCreacion = new DateTime(2026, 9, 11, 4, 0, 40, 691, DateTimeKind.Utc).AddTicks(1141),
                            Monto = 45000.00m,
                            SubastaId = 1,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecioFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<uint>("Version")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "GPU de alta gama para diseño y gaming",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 11, 4, 30, 40, 691, DateTimeKind.Utc).AddTicks(1036),
                            FechaInicio = new DateTime(2026, 9, 11, 3, 45, 40, 691, DateTimeKind.Utc).AddTicks(1031),
                            IncrementoMinimo = 5000.00m,
                            PrecioBase = 30000.00m,
                            Titulo = "Placa de Video RTX",
                            UrlImagen = "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=500",
                            VendedorId = 1,
                            Version = 0u
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Ideal para estaciones de trabajo",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 11, 4, 7, 10, 691, DateTimeKind.Utc).AddTicks(1039),
                            FechaInicio = new DateTime(2026, 9, 11, 3, 7, 40, 691, DateTimeKind.Utc).AddTicks(1039),
                            IncrementoMinimo = 5000.00m,
                            PrecioBase = 50000.00m,
                            Titulo = "Procesador de Alta Gama",
                            UrlImagen = "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=500",
                            VendedorId = 1,
                            Version = 0u
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Descripcion = "Arte y diseño exclusivo",
                            Estado = "PROGRAMADA",
                            FechaFin = new DateTime(2026, 9, 13, 4, 5, 40, 691, DateTimeKind.Utc).AddTicks(1045),
                            FechaInicio = new DateTime(2026, 9, 12, 4, 5, 40, 691, DateTimeKind.Utc).AddTicks(1041),
                            IncrementoMinimo = 2000.00m,
                            PrecioBase = 15000.00m,
                            Titulo = "Figura Coleccionable Edición Limitada",
                            UrlImagen = "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500",
                            VendedorId = 1,
                            Version = 0u
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Descripcion = "Indumentaria clásica",
                            Estado = "FINALIZADA",
                            FechaFin = new DateTime(2026, 9, 11, 2, 5, 40, 691, DateTimeKind.Utc).AddTicks(1050),
                            FechaInicio = new DateTime(2026, 9, 9, 4, 5, 40, 691, DateTimeKind.Utc).AddTicks(1047),
                            IncrementoMinimo = 2000.00m,
                            PrecioBase = 20000.00m,
                            Titulo = "Campera de Cuero Vintage",
                            UrlImagen = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
                            VendedorId = 1,
                            Version = 0u
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            Descripcion = "Sin ofertas registradas",
                            Estado = "DESIERTA",
                            FechaFin = new DateTime(2026, 9, 10, 4, 5, 40, 691, DateTimeKind.Utc).AddTicks(1053),
                            FechaInicio = new DateTime(2026, 9, 8, 4, 5, 40, 691, DateTimeKind.Utc).AddTicks(1052),
                            IncrementoMinimo = 10000.00m,
                            PrecioBase = 80000.00m,
                            Titulo = "Repuesto Clásico de Vehículo",
                            UrlImagen = "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500",
                            VendedorId = 1,
                            Version = 0u
                        });
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.TransactionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.ToTable("TransactionLedgers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 10, 4, 5, 40, 691, DateTimeKind.Utc).AddTicks(1166),
                            Monto = 150000.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 11, 4, 0, 40, 691, DateTimeKind.Utc).AddTicks(1168),
                            Monto = 45000.00m,
                            SubastaId = 1,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Vendedor Test",
                            PasswordHash = "hash_vendedor"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comprador Líder",
                            PasswordHash = "hash_c1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comprador Habilitado",
                            PasswordHash = "hash_c2"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario Sin Fondos",
                            PasswordHash = "hash_sf"
                        });
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Billetera", b =>
                {
                    b.HasOne("PROYECTO_SUBASTA.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("PROYECTO_SUBASTA.Domain.Entities.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Puja", b =>
                {
                    b.HasOne("PROYECTO_SUBASTA.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTO_SUBASTA.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Subasta", b =>
                {
                    b.HasOne("PROYECTO_SUBASTA.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTO_SUBASTA.Domain.Entities.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.TransactionLedger", b =>
                {
                    b.HasOne("PROYECTO_SUBASTA.Domain.Entities.Billetera", "Billetera")
                        .WithMany("Movimientos")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billetera");
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Billetera", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("PROYECTO_SUBASTA.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Billetera")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
